kind: Deployment
metadata:
  name: gogin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gogin
  template:
    metadata:
      labels:
        app: gogin
    spec:
      containers:
      - name: gogin
        image: kushagratandon12/ginimage:2
        command:
        ports:
          - containerPort: 8080